# Generated by Django 4.2.14 on 2024-07-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Модель велосипеда')),
                ('price', models.IntegerField(max_length=4, verbose_name='Стоимость аренды велосипеда за минуту')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'велосипеды',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало аренды')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Конец аренды')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма аренды')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.bike', verbose_name='Модель велосипеда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аренда велосипедов',
                'ordering': ('-start_time',),
            },
        ),
    ]
