# Generated by Django 4.2.14 on 2024-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.CharField(default=1, max_length=256, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость аренды велосипеда за минуту'),
        ),
    ]
