# Generated by Django 4.2.14 on 2024-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_bike_description_alter_bike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Статус велосипеда'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость аренды велосипеда за минуту, руб'),
        ),
    ]
