# Generated by Django 4.2.14 on 2024-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_bike_free_alter_bike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Сумма аренды'),
        ),
    ]
