# Generated by Django 4.2.14 on 2024-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_rental_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Сумма аренды'),
        ),
    ]
