# Generated by Django 4.2.14 on 2024-07-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_rental_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='condition',
            field=models.BooleanField(default=True),
        ),
    ]
