# Generated by Django 4.2.14 on 2024-07-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rental_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='condition',
            field=models.BooleanField(default=True, verbose_name='Арендован'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец аренды'),
        ),
    ]
